const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
const ADD_PRODUCT_BEGIN = "ADD_PRODUCT_BEGIN";
const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
const ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR";
const GET_PRODUCT_BEGIN = "GET_PRODUCT_BEGIN";
const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
const GET_PRODUCT_ERROR = "GET_PRODUCT_ERROR";
const SHOW_ALERT = "SHOW_ALERT";

const IS_DISPLAY = "IS_DISPLAY";
const SORT_PRODUCT_BY_PRICE = "SORT_PRODUCT_BY_PRICE";
const SORT_PRODUCT_BY_TYPE = "SORT_PRODUCT_BY_TYPE";
const PANIGATION = "PANIGATION";
const CHECK_SORT = "CHECK_SORT";
const CHECK_SORT_PRICE = "CHECK_SORT_PRICE";
const CHECK_SORT_MATERIAL = "CHECK_SORT_MATERIAL";
const CHECK_PANIGATION = "CHECK_PANIGATION";
const PRIVIOUS_PAGE = "PRIVIOUS_PAGE";
const GET_CART_ITEMS = "GET_CART_ITEMS";
const ADD_CART_ITEMS_SUCCESS = "ADD_CART_ITEMS_SUCCESS";
const CLEAR_ALERT = "CLEAR_ALERT";
const SORT_PRODUCT_BY_MATERIAL = "SORT_PRODUCT_BY_MATERIAL";
const UPDATE_PRODUCT_IN_CART = "UPDATE_PRODUCT_IN_CART";
const DELETE_PRODUCT_IN_CART = "UPDATE_PRODUCT_IN_CART";
const UPDATE_CHECK_PRODUCT_IN_CART = "UPDATE_CHECK_PRODUCT_IN_CART";
const SET_VOUCHER = "SET_VOUCHER";
const PAYMENT = "PAYMENT";
const LOG_OUT = "LOG_OUT";
// Admin
const GET_ALL_USERS = "GET_ALL_USERS";
const DELETE_USER_BY_ID = "DELETE_USER_BY_ID";
const SET_USER_UPDATE = "SET_USER_UPDATE";
const UPDATE_USER = "UPDATE_USER";

export {
  REGISTER_USER_BEGIN,
  PAYMENT,
  REGISTER_USER_SUCCESS,
  REGISTER_USER_ERROR,
  LOGIN_USER_BEGIN,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_ERROR,
  ADD_PRODUCT_BEGIN,
  ADD_PRODUCT_SUCCESS,
  ADD_PRODUCT_ERROR,
  SHOW_ALERT,
  IS_DISPLAY,
  GET_PRODUCT_BEGIN,
  GET_PRODUCT_SUCCESS,
  GET_PRODUCT_ERROR,
  SORT_PRODUCT_BY_PRICE,
  SORT_PRODUCT_BY_TYPE,
  PANIGATION,
  PRIVIOUS_PAGE,
  CHECK_SORT,
  CHECK_PANIGATION,
  GET_CART_ITEMS,
  CHECK_SORT_PRICE,
  SORT_PRODUCT_BY_MATERIAL,
  CHECK_SORT_MATERIAL,
  UPDATE_PRODUCT_IN_CART,
  DELETE_PRODUCT_IN_CART,
  ADD_CART_ITEMS_SUCCESS,
  CLEAR_ALERT,
  UPDATE_CHECK_PRODUCT_IN_CART,
  SET_VOUCHER,
  LOG_OUT,
  GET_ALL_USERS,
  DELETE_USER_BY_ID,
  SET_USER_UPDATE,
  UPDATE_USER,
};
